### PR TITLE
Use ntStat in ntEdit

### PR DESCRIPTION
**Pull request by lcoombe**
* Replace ntHits with the newer ntStat
* Update demo files

### CODE REVIEW

**Review by jwcodee — APPROVED** [review]
Thanks.

**Review by warrenlr — COMMENTED** [review]
looks good to me! If we haven't done so, let's double-check that the new -e snakemake/ntStat option does not have collisions with ntEdit. Note: in ntedit, -e is a secondary BF input :: -e,	secondary BF with k-mers to reject (generated from ntHits v1.0.1+), OPTIONAL - NOT NEEDED with CBF.  

Also note the couple mentions of ntHits in the "Usage" section of ntEdit:

	-r,	Bloom filter (BF) or counting BF (CBF) file (generated from ntHits v1.0.1+), REQUIRED
	-e,	secondary BF with k-mers to reject (generated from ntHits v1.0.1+), OPTIONAL - NOT NEEDED with CBF

**Comment by lcoombe** [comment]
> looks good to me! If we haven't done so, let's double-check that the new -e snakemake/ntStat option does not have collisions with ntEdit. Note: in ntedit, -e is a secondary BF input :: -e, secondary BF with k-mers to reject (generated from ntHits v1.0.1+), OPTIONAL - NOT NEEDED with CBF.
> 
> Also note the couple mentions of ntHits in the "Usage" section of ntEdit:
> 
> ```
> -r,	Bloom filter (BF) or counting BF (CBF) file (generated from ntHits v1.0.1+), REQUIRED
> -e,	secondary BF with k-mers to reject (generated from ntHits v1.0.1+), OPTIONAL - NOT NEEDED with CBF
> ```

Thanks Rene!
For collisions - luckily that is only an issue with Makefiles, not snakemake files. For Makefiles calling other Makefiles, the parameters can cascade unexpectedly, but that luckily cannot happen with calling a binary from a snakemake file. 

For those ntHits mentions that you quoted - I believe they are already changed in `ntedit.cpp` - Or did you see them elsewhere that I may have missed ?

**Review by warrenlr — APPROVED** [review]
perfect, I hadn't seen the ntedit.cpp. Thanks for making all those changes @lcoombe !

**Review by parham-k — APPROVED** [review]
Looks good to me! Thank you @lcoombe.

**Pull request merged**
